# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"



target "ember" do
platform :ios, '7.0'
pod 'RestKit'
pod 'CocoaLumberjack'
end

target "emberTests" do

end

